### ISSUE TITLE
ElasticSearch 2.0

### ISSUE THREAD

**Issue by dylanmei** [ewr/elasticsearch_exporter#8]
There are [quite a few changes](https://github.com/elastic/elasticsearch/blob/148265bd164cd5a614cd020fb480d5974f523d81/docs/reference/migration/migrate_2_0/stats.asciidoc) in ElasticSearch 2.0, one of which breaks the JSON deserialization.

What kind of plan would you take for supporting 1.x/2.x?

**Comment by ewr** [comment]
That's a good question... I haven't had a chance to use 2.0 yet, because I've been waiting to see how support lands in the Chef cookbook.

Is the break from an element removal or something getting renamed / moved?

**Comment by dylanmei** [comment]
The break is because NodeStatsOSResponse.LoadAvg is a float64 rather than float6r

**Comment by keis** [comment]
I looks like LoadAvg is never used so it should be fine to delete that and be compatible with both 1.x and 2.x. wdyt?

**Comment by ewr** [comment]
I apologize for leaving this hanging. Let me pull down ES 2.x right now and take a look.

**Comment by ewr** [comment]
Ok, @keis / @dylanmei, give that a shot.

**Comment by dylanmei** [comment]
I've pointed this at a busy cluster and the metrics endpoint looks great. I've not checked the accuracy of the data -- I'll follow up with a different issue if there's anything unexpected for 2.0.

Thanks!

**Comment by keis** [comment]
[![LGTM](http://lgtm.in/p/PrW1)](http://lgtm.in/i/PrW1)
